POST http://localhost:8080/api/user-balance/keira/

GET http://localhost:8080/api/user-balance/d4fff456-2665qfwfsadgafbcfbffec4eb6/

GET http://localhost:8080/api/user-balance/d4fff456-2665-4191-b5f5-bcfbffec4eb6/

PUT http://localhost:8080/api/user-balance/d4fff456-2665-4191-b5f5-bcfbffec4eb6/topup/ HTTP/1.1
Content-Type: application/json

{
    "amount" : "5000.0"
}

PUT http://localhost:8080/api/user-balance/d4fff456-2665-4191-b5f5-bcfbffec4eb6/withdraw/ HTTP/1.1
Content-Type: application/json

{
    "amount" : "4000.0"
}


GET http://localhost:8080/api/transaction/item/c43a946a-bdb9-44d9-84d2-70f24c17885e/ HTTP/1.1

POST http://localhost:8080/api/transaction/owner/c43a946a-bdb9-44d9-84d2-70f24c17885e/ HTTP/1.1
Content-Type: application/json

{
    "amount" : "5000.0",
    "transactionType": "TOPUP"
}

GET http://localhost:8080/api/transaction/owner/c43a946a-bdb9-44d9-84d2-70f24c17885e/ HTTP/1.1